### ISSUE TITLE
Improve Empty Page Heuristic

### ISSUE THREAD

**Issue by JonasRSV** [Marcus9512/Judging-an-academic-paper-by-its-cover#12]
If current empty page heuristic is not good enough, make it better.

**Comment by JonasRSV** [comment]
See: https://github.com/Marcus9512/dd2430/blob/master/src/Tools/open_review_downloader.py#L221

Feel free to ask me if you want to do this.

**Comment by loalm** [comment]
@JonasRSV Kunde vi kolla om t.ex. 'ABSTRACT' strängen finns med på sidan? Om jag nu förstår problemet rätt vill vi identifiera förstasidan. Kommer dock inte på någon bättre heuristik.

**Comment by JonasRSV** [comment]
Det skulle kanske kunna vara en grej, kan vara vart att se att det inte leder till att massa papper droppas
