### ISSUE TITLE
Dokument Dataset

### ISSUE THREAD

**Issue by Marcus9512** [Marcus9512/Judging-an-academic-paper-by-its-cover#7]
What is required from our dataset? 

- Specify all necessary data points to a document.
- Why are we choosing those datapoints?
- What is the format of the dataset?
- How much data do we need?

**Comment by Marcus9512** [comment]
For next week, how many paper from each year, how accepted, how many that are rejected. (ICLR)

**Comment by JonasRSV** [comment]
ICLR 2020 

~1600 Rejected
~ 600 Accepted
